# Workflow simple pour déployer du contenu statique sur GitHub Pages
name: Déployer du contenu statique sur Pages

on:
  # Se déclenche sur les poussées ciblant la branche par défaut
  push:
    branches: ["main"]

  # Permet d'exécuter ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

# Définit les autorisations du jeton GITHUB_TOKEN pour autoriser le déploiement sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Autorise un seul déploiement simultané, en sautant les exécutions en attente entre l'exécution en cours et la dernière en file d'attente.
# Cependant, NE PAS annuler les exécutions en cours car nous voulons permettre à ces déploiements de production de se terminer.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job unique de déploiement car nous ne faisons que déployer
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configuration de Pages
        uses: actions/configure-pages@v5
      - name: Télécharger l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          # Télécharger l'intégralité du dépôt
          path: '.'
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
